[tool.poetry]
name = "address-book-full"
version = "0.1.0"
description = "Address Book"
authors = ["Sergii Pryima"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
