"""Init

Revision ID: ea5783728fe8
Revises: 
Create Date: 2023-10-07 17:13:06.507386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5783728fe8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('subj_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subj_name')
    )
    op.create_table('students',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.Column('subj_name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subj_name_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboard',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subj_name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subj_name'], ['subjects.subj_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboard')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_table('groups')
    # ### end Alembic commands ###
